In [8]:
import numpy as np

In [2]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

In [3]:
arr = np.array(list)

In [7]:
print(4 * arr)

[ 80 108  36  48 124  68  16 200 156 140]


In [9]:
print("Mean =", np.mean(arr))

Mean = 24.4


In [10]:
print("Median =", np.median(arr))

Median = 23.5


In [11]:
print("Standard deviation =", np.std(arr))


Standard deviation = 13.828955130450023


In [12]:
min_index = np.argmin(arr)
max_index = np.argmax(arr)
print("Index of smallest value:", min_index)
print("Index of largest value:", max_index)

Index of smallest value: 6
Index of largest value: 7


In [13]:
print("Smallest value:", arr[min_index])
print("Largest value:", arr[max_index])

Smallest value: 4
Largest value: 50


In [15]:
print("np.min(arr) =", np.min(arr))
print("np.max(arr) =", np.max(arr))

np.min(arr) = 4
np.max(arr) = 50


In [16]:
greater_than_20 = arr[arr > 20]
print("Values greater than 20:", greater_than_20)

Values greater than 20: [27 31 50 39 35]


In [17]:
matrix = np.array([
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
])

In [18]:
print("Shape:", matrix.shape)

Shape: (3, 4)


In [19]:
rows, cols = matrix.shape
print("Rows:", rows)
print("Columns:", cols)

Rows: 3
Columns: 4


In [20]:
print("Third column:", matrix[:, 2])

Third column: [17 14 19]


In [22]:
print("Second row:", matrix[1])

Second row: [ 8 21 14  3]


In [24]:
print(matrix * 2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [34]:
print(np.mean(matrix[:,0])) # col 1

6.333333333333333


In [35]:
print(np.mean(matrix[:,1])) # col 2

15.333333333333334


In [36]:
print(np.mean(matrix[:,2])) # col 3

16.666666666666668


In [38]:
print(np.mean(matrix[:,3])) # col 4

7.666666666666667


In [40]:
print(np.mean(matrix)) # overall mean

11.5


In [42]:
print("Max of each row:", np.max(matrix, axis=1))
print("Min of each column:", np.min(matrix, axis=0))

Max of each row: [17 21 19]
Min of each column: [ 5 12 14  3]


In [43]:
flat = matrix.flatten()
print("Flattened array:", flat)
print("New shape:", flat.shape)

Flattened array: [ 5 12 17  9  8 21 14  3  6 13 19 11]
New shape: (12,)


In [44]:
flat_min_index = np.argmin(flat)
flat_max_index = np.argmax(flat)
print("Flat index of smallest value:", flat_min_index)
print("Flat index of largest value:", flat_max_index)

Flat index of smallest value: 7
Flat index of largest value: 5


In [45]:
min_coords = np.unravel_index(flat_min_index, matrix.shape)
max_coords = np.unravel_index(flat_max_index, matrix.shape)
print("Coordinates of smallest value:", min_coords)
print("Coordinates of largest value:", max_coords)

Coordinates of smallest value: (np.int64(1), np.int64(3))
Coordinates of largest value: (np.int64(1), np.int64(1))


In [46]:
greater_than_15 = matrix[matrix > 15]
print("Values greater than 15:", greater_than_15)

Values greater than 15: [17 21 19]


In [49]:
sorted_rows = np.sort(matrix, axis=1)

print(sorted_rows)

[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [ ]:
# 4 Prime Star Systems - come back and finish this one later

In [1]:
# 5 Let’s Play Checkers!

In [9]:
def zeroArray():
    return np.zeros((8, 8))

In [10]:
zeroArray()

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
def oddRowPattern():
    arr = np.zeros((8, 8), dtype=int)
    
    pattern = np.array([1, 0] * 4) 
    
    arr[1] = pattern
    arr[3] = pattern
    arr[5] = pattern
    arr[7] = pattern
    
    return arr

In [13]:
oddRowPattern()

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [14]:
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    pattern1 = np.array([1, 0] * 4)
    pattern2 = np.array([0, 1] * 4)
    
    board[0] = pattern1
    board[1] = pattern2
    board[2] = pattern1
    board[3] = pattern2
    board[4] = pattern1
    board[5] = pattern2
    board[6] = pattern1
    board[7] = pattern2
    
    return board

In [16]:
checkerboard()

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [18]:
def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    pattern1 = np.array([0, 1] * 4)
    pattern2 = np.array([1, 0] * 4)

    board[0] = pattern1
    board[1] = pattern2
    board[2] = pattern1
    board[3] = pattern2
    board[4] = pattern1
    board[5] = pattern2
    board[6] = pattern1
    board[7] = pattern2

    return board

In [19]:
reverse_checkerboard()

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [20]:
#6 The Expanding Universe

In [25]:
def expansion(arr, n):
    result = []
    spaces = " " * n     
    
    for word in arr:
        new_word = ""    
        for i in range(len(word)):
            new_word = new_word + word[i]  
            if i != len(word) - 1:
                new_word = new_word + spaces   
        result.append(new_word)
    return np.array(result)

In [26]:
expansion("word", 1)

array(['w', 'o', 'r', 'd'], dtype='<U1')

In [27]:
def secondDimmest(arr):
    result = []
    
    for row in arr:   
        sorted_row = np.sort(row)
        second_brightest = sorted_row[-2]
        result.append(second_brightest)
    return np.array(result)