In [2]:
import numpy as np

In [2]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

In [3]:
arr = np.array(list)

In [5]:
arr4 = arr*4
print(arr4)

[ 80 108  36  48 124  68  16 200 156 140]


In [6]:
print(np.mean(arr))

24.4


In [7]:
print(np.median(arr))

23.5


In [8]:
print(np.std(arr))

13.828955130450023


In [9]:
np.argmin(arr)

np.int64(6)

In [10]:
np.argmax(arr)

np.int64(7)

In [14]:
print(arr[np.argmax(arr)])

50


In [15]:
print(arr[np.argmin(arr)])

4


In [18]:
print(np.max(arr))

50


In [19]:
print(np.min(arr))

4


In [20]:
mask = arr > 20
result = arr[mask]
print(result)

[27 31 50 39 35]


In [27]:
matrix = [
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
]
A = np.array(matrix)

In [30]:
print(A.shape)

(3, 4)


In [31]:
third_col = A[:, 2]
print(third_col)

[17 14 19]


In [33]:
second_row = A[1,: ]
print(second_row)

[ 8 21 14  3]


In [34]:
print(2*A) # multiply each index by 2

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [39]:
print(np.mean(A[:,0])) # mean of column 1

6.333333333333333


In [40]:
print(np.mean(A[:,1])) # mean of column 2

15.333333333333334


In [41]:
print(np.mean(A[:,2])) # mean of column 3

16.666666666666668


In [42]:
print(np.mean(A)) # mean of entire coloumn 

11.5


In [46]:
print(np.max(A[0,:])) # max of row 1

17


In [47]:
print(np.max(A[1,:])) # max of row 2

21


In [48]:
print(np.max(A[2,:])) # max of row 3

19


In [50]:
print(np.min(A[:,0])) # min of column 1

5


In [51]:
print(np.min(A[:,1])) # min of column 2

12


In [52]:
print(np.min(A[:,2])) # min of column 3

14


In [53]:
print(np.min(A[:,3])) # min of column 4

3


In [60]:
B = A.flatten()

In [61]:
print(B)

[ 5 12 17  9  8 21 14  3  6 13 19 11]


In [57]:
print(B.shape)

(12,)


In [58]:
print(np.argmin(B))

7


In [59]:
print(np.argmax(B))

5


In [68]:
np.unravel_index(1, A.shape) # confused

(np.int64(0), np.int64(1))

In [69]:
mask = B > 15

In [71]:
print(B[mask])

[17 21 19]


In [74]:
np.sort(A[0,:])

array([ 5,  9, 12, 17])

In [75]:
np.sort(A[1,:])

array([ 3,  8, 14, 21])

In [76]:
np.sort(A[2,:])

array([ 6, 11, 13, 19])

In [81]:
arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

In [162]:
primes = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

In [163]:
def make_zeros_8x8():
    return np.zeros((8, 8))

In [164]:
arr = np.array([0,0,0])

In [165]:
print(arr)

[0 0 0]


In [166]:
b = arr.copy()

In [167]:
print(b)

[0 0 0]


In [168]:
b[0::2] = 1

In [169]:
print(b)

[1 0 1]


In [170]:
matrix = make_zeros_8x8()

In [171]:
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [185]:
def create_checkerboard(array):
    arr = array.copy()
    for i in range(7):
        if i % 2 == 0:
            arr[i,::2] = 1
        else:
            arr[i,1::2] = 1
    return arr

In [186]:
new_matrix = create_checkerboard(matrix)

In [187]:
print(new_matrix)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [191]:
def create_off_checkerboard(array):
    arr = array.copy()
    for i in range(7):
        if i % 2 == 0:
            arr[i,1::2] = 1
        else:
            arr[i,::2] = 1
    return arr

In [192]:
new_matrix1 = create_off_checkerboard(matrix)

In [193]:
print(new_matrix1)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
def add_space(word, n):
    word = word.copy()
    
        

In [254]:
a = np.array(["abc", "cde"])

In [235]:
b = np.array([])

In [236]:
print(b)

[]


In [237]:
b = a[0][0] + " " + a[0][1]

In [255]:
print(a)

['abc' 'cde']


In [240]:
print(b)

a b


In [263]:
new_word = np.insert(a, 1, " ", 0)

In [264]:
print(new_word)

['abc' ' ' 'cde']


In [169]:
def secondDimmest(array):
    return np.partition(array, -2, axis=1)[:, -2]
    second_largest = array1[:, -2]
    return second_largest


In [180]:
np.random.seed(123)

In [181]:
stars = np.random.randint(500, 2000, (5, 5))

In [182]:
secondDimmest(stars)

array([1889, 1647, 1138, 1863, 1592])

In [183]:
print(stars)

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
